# Generated by Django 4.0.5 on 2022-08-31 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_channel_people_channel_alter_invite_channel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Channel_people',
            new_name='Channel_person',
        ),
        migrations.CreateModel(
            name='Channel_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_messages', to='chat.channel')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
