# Generated by Django 4.0.5 on 2022-08-31 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_invite_channel_people_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel_people',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='chat.channel'),
        ),
        migrations.AlterField(
            model_name='invite',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invites', to='chat.channel'),
        ),
    ]
